# Info
info.app:
  name: ${project.name}
  description: ${project.description}
  version: ${project.version}

# Actuator
management:
  endpoints.web.exposure.include: '*'
  endpoint.health.show-details: always

# Various
spring.application.name: ${project.name}
server.port: 8080
spring.boot.admin.client:
  url: http://localhost:82
  username: admin
  password: admin

spring.mvc.format.date: 'yyyy-MM-dd'

# Logging levels
logging.level:
  root: WARN
  ${project.group}: INFO

# Disable Groovy templates
spring.groovy.template:
  check-template-location: false
  enabled: false

# Resilience
resilience4j.retry.instances:
  SunEphemerisProvider:
    maxRetryAttempts: 6
    waitDuration: 1s
    enableExponentialBackoff: true
    exponentialBackoffMultiplier: 2
  SunEventPublishScheduler:
    maxRetryAttempts: 120
    waitDuration: 60s

# Application
init-on-startup: true
location:
  latitude: 52.23
  longitude: 21.01
provider.path: 'https://api.sunrise-sunset.org:443'
scheduler.cron: '0 0 0 * * *'
publisher:
  lock-duration: 3m
  channel: 'sun-ephemeris:events'