version: '3.8'
services:
  redis:
    image: redis:6.0.9-alpine
    networks:
      dev_network:
        aliases: [cache]
    ports:
      - 6379:6379

  spring-boot-admin:
    image: slydeveloper/spring-boot-admin:latest
    ports:
      - 82:1111
    environment:
      - spring_boot_admin_security_enabled=true
      - spring_security_user_name=admin
      - spring_security_user_password=admin

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    ports:
      - 83:8080
    environment:
      - URL=http://localhost:8080/v3/api-docs

networks:
  dev_network: