@startuml

Cron -> PublishScheduler : scheduleEvents
activate PublishScheduler
    PublishScheduler -> Provider : sunEphemerisFor(date)
    activate Provider
        database Redis
        Provider -> Redis : get(date)
        note right : Annotation declarative cache
        activate Redis
            Provider <-- Redis : null
        deactivate Redis
        boundary SunriseAPI
        Provider -> SunriseAPI : HTTP
        note right : OpenAPI generated client
        activate SunriseAPI
            Provider <-- SunriseAPI : JSON
        deactivate SunriseAPI
        Provider -> Redis : set
        note right : Annotation declarative cache
        PublishScheduler <-- Provider : Ephemeris
    deactivate Provider

    loop for each Event
        create Publisher
        PublishScheduler -> Publisher : new
        PublishScheduler -> TaskScheduler : schedule(task)
    end

    Cron <-- PublishScheduler
deactivate PublishScheduler

... Later, same day ...

loop for each Event
    TaskScheduler -> Publisher : run
    activate Publisher
        Publisher -> Redis : acquire lock
        note left : Annotation declarative lock
        activate Redis
            Publisher <-- Redis : lock
        deactivate Redis
        Publisher -> Redis : enqueue
        TaskScheduler <-- Publisher
    deactivate Publisher
end

@enduml

