@startuml

Cron -> SunEventPublishScheduler : scheduleEvents
activate SunEventPublishScheduler
    SunEventPublishScheduler -> SunEphemerisProvider : sunEphemerisFor(today)
    activate SunEphemerisProvider
        database Redis
        SunEphemerisProvider -> Redis : get(date)
        activate Redis
            SunEphemerisProvider <-- Redis : null
        deactivate Redis
        boundary SunriseSunset
        SunEphemerisProvider ->x SunriseSunset : HTTP
        SunEphemerisProvider ->x SunriseSunset : HTTP
        note right : Failed request retries...
        SunEphemerisProvider ->x SunriseSunset : HTTP
        SunEventPublishScheduler <-- SunEphemerisProvider : error
        note right : Retry limit has been reached
    deactivate SunEphemerisProvider

    note right of SunEventPublishScheduler : Annotation declarative fallback
    SunEventPublishScheduler -> SunEphemerisProvider : sunEphemerisFor(yesterday)
    activate SunEphemerisProvider
        SunEphemerisProvider -> Redis : get(date - 1)
        activate Redis
            SunEphemerisProvider <-- Redis : SunEphemeris
        deactivate Redis
        SunEventPublishScheduler <-- SunEphemerisProvider : SunEphemeris
    deactivate SunEphemerisProvider

    note right of SunEventPublishScheduler : Publisher setup same as on a happy path

    Cron <-- SunEventPublishScheduler
deactivate SunEventPublishScheduler

@enduml

